### DISCUSSION TITLE
v0.4 Beta 1

### DISCUSSION THREAD

**Discussion by BeardedTek** [BeardedTek-com/fEVR#26] [Announcements]
# Initial beta release featuring new features of the v0.4 release.

- Although beta, this is the most stable release yet!
- Includes tailscale as a sidecar container to provide secure access to fEVR.
- fEVR must be able to communicate with your instance of fEVR to work properly.  It is recommended to either install tailscale in your frigate stack or even include frigate in this stack.

<hr /><em>This discussion was created from the release <a href='https://github.com/BeardedTek-com/fEVR/releases/tag/v0.4-beta-01'>v0.4 Beta 1</a>.</em>

**Comment by renarena** [comment]
Can fEVR be used locally without tailscale?

**Reply by BeardedTek** [reply]
It most certainly can.  Tailscale is 100% optional.


I use it for communication off-site.  I put tailscale on my phone and never have to open a firewall port if I want to check on it.

**Reply by BeardedTek** [reply]
Just uncomment or delete the tailscale section of the docker-compose.

**Comment by renarena** [comment]
Ok.
I tried it.
Was not sure what to put in there (i am fairly new to docker), but inserting my network details seems wrong.
Now i cannot reach my host VM  per ssh anymore, even after i stopped the docker service in proxmox web interface...
```
NETWORK_NAME=beardnet
NETWORK_SUBNET=192.168.200.0/24
NETWORK_GATEWAY=192.168.200.1
```

**Reply by BeardedTek** [reply]
You want this to be a separate subnet from yours.

Typically most home routers use 192.168.2.0/24 or 192.168.1.0/24.

The default settings should be safe in 99% of situations

If you enter your own networks details it will cause weird things to happen because of multiple IP addresses on the same subnet.

If you are running fEVR standalone, I recommend adding a ports section to your docker-compose.

Here is a docker-compose you should be able to drop in...


```
version: '2.4'
services:
  fevr:
    build:
      context: ${FEVR_CONTEXT}
      dockerfile: Dockerfile
    image: ${FEVR_IMAGE:-ghcr.io/beardedtek-com/fevr:main}
    container_name: ${FEVR_CONTAINER_NAME:-fevr}
    restart: unless-stopped
    environment:
      FRIGATE_URL: "${FRIGATE_URL:-http://frigate.local:5000}"
      FEVR_DEBUG: "${FRIGATE_DEBUG:-true}"
      FEVR_IP: ${FEVR_IP:-192.168.200.2}
      FEVR_PORT: ${FEVR_PORT:-5080}
      FEVR_CONTAINER_NAME: ${FEVR_CONTAINER_NAME:-fevr}
      MQTT_BROKER_URL: ${MQTT_BROKER_URL:-192.168.2.245}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT:-1883}
      MQTT_USER: ${MQTT_USER:-}
      MQTT PASS: ${MQTT_PASS:-}
      MQTT_TOPICS: ${MQTT_TOPICS:-'frigate/+'}
    privileged: true
    ports:
      - 5080:5080
    volumes:
     - ./vol/fevr/data/:/var/www/data                              # OPTIONAL: expose /var/www/data folder which contains the SQLite database and config.json files
     - ./vol/fevr/events:/var/www/html/events                      # OPTIONAL: save events to a local folder
     #- nfsevents:/var/www/html/events                             # OPTIONAL: save events to an NFS share
     #- nfsdata:/var/www/data                                      # OPTIONAL: save conig data to an NFS share

#volumes:                                                          # Uncomment this section if you wish to use NFS
#  nfsevents:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NAS_IP},nfsvers=4"
#      device: ":${NAS_EVENTS}"
#  nfsdata:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NAS_IP},nfsvers=4"
#      device: ":${NAS_DATA}"

```

**Comment by renarena** [comment]
Thank you very much!
with `docker network rm fevr_beardnet` i got the wrong bridge deleted and i can reach the VM again (in case someone else has the same problem ;-) .
If i try to access fevr using the IP of the VM, 192.168.1.224:5080/cgi-bin/index.py i get "Internal Server Error".
(https://fevr.local:5080 or http://fevr.local:5080 does not work)

**Reply by BeardedTek** [reply]
I've been having issues with setup with the v0.5 branch and earlier which is why I'm developing in flask for the future in v0.6.

Can you run the following and post the output:
```
docker-compose logs --tail=100 fevr
```
and post it here

**Comment by renarena** [comment]
seems like my mqtt settings are wrong

Attaching to fevr-devel
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out

**Reply by BeardedTek** [reply]
can you run the following:
```
docker-compose exec fevr ps
```

and

```
docker-compose exec fevr ls -la /var/www/
```

and post it back here

**Comment by renarena** [comment]
I changed the mqtt pwd to a working one.
Now i get something about
```
fevr-devel | [ index.py       ] 1649973737.9306 execute() : frigateConfig('http://frigate.local:5000')
fevr-devel | [ frigateConfig.py] 1649973737.9983 Contacting frigate: http://frigate.local:5000/api/config
fevr-devel | [ frigateConfig.py] 1649973738.0151 Contacting frigate: http://frigate.local:5000/api/config - ERROR
```

but i have set frigate url to an IP address.

```
#  docker-compose exec fevr ps
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   39 root      0:00 s6-supervise s6-fdholderd
  220 root      0:00 s6-supervise fevr
  221 root      0:00 s6-supervise mqtt_client
  222 root      0:00 s6-supervise sqlite_web
  225 root      0:00 {run} /bin/bash ./run
  226 root      0:00 {run} /bin/bash ./run
  243 root      0:00 httpd -DFOREGROUND
  246 root      0:00 {sqlite_web} /usr/bin/python3 /usr/bin/sqlite_web -p 5081 
  251 apache    0:00 httpd -DFOREGROUND
  252 apache    0:00 httpd -DFOREGROUND
  253 apache    0:00 httpd -DFOREGROUND
  254 apache    0:00 httpd -DFOREGROUND
  595 root      0:00 {run} /bin/bash ./run
  596 root      0:00 {mqtt_client} /usr/bin/python /opt/fevr/startup/mqtt_clien
  597 root      0:00 ps
```
```
# docker-compose exec fevr ls -la /var/www/
total 44
drwxrwx---    1 apache   1000          4096 Apr 14 14:08 .
drwxr-xr-x    1 root     root          4096 Apr 14 14:08 ..
drwxrwx---    4 apache   apache        4096 Apr 14 14:08 data
drwxrwx---    1 apache   1000          4096 Apr 14 14:08 default
drwxrwx---    1 apache   1000          4096 Apr 14 20:24 html
drwxrwx---    1 apache   1000          4096 Apr 14 20:24 localhost
drwxrwx---    1 apache   1000          4096 Apr 14 14:08 logs
lrwxrwxrwx    1 apache   1000            16 Apr 14 20:24 modules -> /usr/lib/apache2
lrwxrwxrwx    1 apache   1000            12 Apr 14 20:24 run -> /run/apache2

```

**Comment by renarena** [comment]
```

fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out
fevr-devel | 192.168.1.40 - - [14/Apr/2022:22:02:17 +0000] "GET / HTTP/1.1" 200 119
fevr-devel | 192.168.1.40 - - [14/Apr/2022:22:02:17 +0000] "GET / HTTP/1.1" 200 119 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
fevr-devel | [ index.py       ] 1649973737.9306 execute() : frigateConfig('http://frigate.local:5000')
fevr-devel | [ frigateConfig.py] 1649973737.9983 Contacting frigate: http://frigate.local:5000/api/config
fevr-devel | [ frigateConfig.py] 1649973738.0151 Contacting frigate: http://frigate.local:5000/api/config - ERROR
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/var/www/html/cgi-bin/index.py", line 194, in <module>
fevr-devel |     main()
fevr-devel |   File "/var/www/html/cgi-bin/index.py", line 192, in main
fevr-devel |     fevr()
fevr-devel |   File "/var/www/html/cgi-bin/index.py", line 41, in __init__
fevr-devel |     self.execute()
fevr-devel |   File "/var/www/html/cgi-bin/index.py", line 176, in execute
fevr-devel |     self.genSettings()
fevr-devel |   File "/var/www/html/cgi-bin/index.py", line 105, in genSettings
fevr-devel |     if self.myConfig['fevr']['clock'] == '12':
fevr-devel | KeyError: 'clock'
fevr-devel | [Thu Apr 14 22:02:18.024899 2022] [cgid:error] [pid 252:tid 140135829871416] [client 192.168.1.40:51400] End of script output before headers: index.py
fevr-devel | 192.168.1.40 - - [14/Apr/2022:22:02:17 +0000] "GET /cgi-bin/index.py HTTP/1.1" 500 607
fevr-devel | 192.168.1.40 - - [14/Apr/2022:22:02:17 +0000] "GET /cgi-bin/index.py HTTP/1.1" 500 607 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
fevr-devel | 192.168.1.40 - - [14/Apr/2022:22:02:18 +0000] "GET /favicon.ico HTTP/1.1" 200 1470
fevr-devel | 192.168.1.40 - - [14/Apr/2022:22:02:18 +0000] "GET /favicon.ico HTTP/1.1" 200 1470 "http://192.168.1.224:5080/cgi-bin/index.py" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out

```

**Reply by BeardedTek** [reply]
can you run:
```
docker-compose exec fevr ls -la /var/www/data/db
docker-compose exec fevr ls -la /var/www/data/config
```

I'm have a feeling its an issue with permissions or a file that didn't get packaged correctly.

**Comment by BeardedTek** [comment]
```
fevr-devel | [ index.py       ] 1649973737.9306 execute() : frigateConfig('http://frigate.local:5000')
fevr-devel | [ frigateConfig.py] 1649973737.9983 Contacting frigate: http://frigate.local:5000/api/config
fevr-devel | [ frigateConfig.py] 1649973738.0151 Contacting frigate: http://frigate.local:5000/api/config
```
Just saw this.  It looks like your config isn't being passed through...

Try running:
```
docker-compose exec fevr nano /var/www/data/config/config.json
```
edit the contents to reflect your setup
save the file <ctrl-s><ctrl-x>
If you prefer vi, run:
```
docker-compose exec fevr vi /var/www/data/config/config.json
```

and try accessing the page again.

**Comment by renarena** [comment]
changed the fever address, but there are no mqtt settings in the config.json
so still mqtt connection timeout errors

```  GNU nano 5.7                                 /var/www/data/config/config.json                                            
{
  "config": "/var/www/data/config/config.json",
  "fevr": {
    "base": "/var/www/",
    "db": "/var/www/data/db/fEVR.sqlite",
    "debug": "true",
    "html": "/var/www/html",
    "title": "Home"
  },
  "frigate": {
    "apiEventPath": "/api/events/",
    "clipPath": "/clip.mp4",
    "snapPath": "/snapshot.jpg",
    "url": "http://192.168.1.222:5000"
  }
}
```
```
-rwxrwx---    1 apache   apache       24576 Apr 14 14:08 fEVR.sqlite

-rwxrwx---    1 apache   apache         362 Apr 15 07:23 config.json
```

**Reply by BeardedTek** [reply]
In docker-compose.yml please add quotes to the following line:
```

MQTT_BROKER_URL: ${MQTT_BROKER_URL:-192.168.2.245}
```
changes to:
```
MQTT_BROKER_URL: "${MQTT_BROKER_URL:-192.168.2.245}"
```
 Then run:
```
docker-compose down && docker-compose up -d
```

**Comment by renarena** [comment]
if i do docker-compose up i get

`fevr-devel |         Starting fEVR on http://:5080` - looks wrong
 
```
docker-compose up
Creating network "fevr_default" with the default driver
Creating fevr-devel ... done
Attaching to fevr-devel
fevr-devel | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
fevr-devel | [s6-init] ensuring user provided files have correct perms...exited 0.
fevr-devel | [fix-attrs.d] applying ownership & permissions fixes...
fevr-devel | [fix-attrs.d] done.
fevr-devel | [cont-init.d] executing container initialization scripts...
fevr-devel | [cont-init.d] done.
fevr-devel | [services.d] starting services
fevr-devel | 
fevr-devel | 
fevr-devel |         Starting fEVR on http://:5080
fevr-devel | 
fevr-devel | 
fevr-devel | 
fevr-devel | 
fevr-devel |       Starting sqlite web at http://172.20.0.2:5081
fevr-devel | 
fevr-devel | 
fevr-devel | [Fri Apr 15 16:57:06.222649 2022] [mpm_event:notice] [pid 234:tid 140150253816648] AH00489: Apache/2.4.53 (Unix) configured -- resuming normal operations
fevr-devel | [Fri Apr 15 16:57:06.222674 2022] [core:notice] [pid 234:tid 140150253816648] AH00094: Command line: 'httpd -D FOREGROUND'
fevr-devel | [services.d] done.
fevr-devel |  * Serving Flask app 'sqlite_web.sqlite_web' (lazy loading)
fevr-devel |  * Environment: production
fevr-devel |    WARNING: This is a development server. Do not use it in a production deployment.
fevr-devel |    Use a production WSGI server instead.
fevr-devel |  * Debug mode: off
fevr-devel |  * Running on all addresses (0.0.0.0)
fevr-devel |    WARNING: This is a development server. Do not use it in a production deployment.
fevr-devel |  * Running on http://127.0.0.1:5081
fevr-devel |  * Running on http://172.20.0.2:5081 (Press CTRL+C to quit)
fevr-devel | Traceback (most recent call last):
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 238, in <module>
fevr-devel |     fevrMQTT()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 131, in __init__
fevr-devel |     self.run()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 233, in run
fevr-devel |     self.client = self.connect_mqtt()
fevr-devel |   File "/opt/fevr/startup/mqtt_client", line 166, in connect_mqtt
fevr-devel |     client.connect(self.broker, self.port)
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
fevr-devel |     return self.reconnect()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
fevr-devel |     sock = self._create_socket_connection()
fevr-devel |   File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
fevr-devel |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
fevr-devel |     raise err
fevr-devel |   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
fevr-devel |     sock.connect(sa)
fevr-devel | socket.timeout: timed out
fevr-devel | Traceback (most recent call last):
```

**Comment by renarena** [comment]
.env
```
# Bridge Network Details
NETWORK_NAME=beardnet
NETWORK_SUBNET=192.168.200.0/24
NETWORK_GATEWAY=192.168.200.1

# Tailscale Container Variables
#TAILSCALE_IP=192.168.200.3
#TAILSCALE_IMAGE=ghcr.io/beardedtek-com/tailscale:main
#TAILSCALE_CONTAINER_NAME=tailscale-devel
#TAILSCALE_CONTEXT=./docker/tailscale/
#TAILSCALE_DATA=./vol/tailscale/data
#TAILSCALE_VAR_LIB=./vol/tailscale/var_lib
#TAILSCALE_COMMAND=/opt/tailscale/tailscale

# fEVR Container Variables
FEVR_IP=192.168.200.2
FEVR_IMAGE=ghcr.io/beardedtek-com/fevr:main
FEVR_CONTAINER_NAME=fevr-devel
FEVR_CONTEXT=./docker/fEVR/
FEVR_DEBUG=true
FEVR_TITLE=Home
FRGIGATE_URL=http://192.168.1.222:5000

# OPTIONAL NAS
#NAS_IP=192.168.1.100
#NAS_EVENTS=/export/fevr
#NAS_DATA=/export/fevr_data

# MQTT
MQTT_BROKER_URL=192.168.1.222
MQTT_BROKER_PORT=1883
MQTT_USER=user
MQTT_PASS=password

# comma seperated list of topics
# Default: 'frigate/available,frigate/events,frigate/stats'
# Debugging: 'frigate/+
# limited to 5 topics, all extras will be dropped.
MQTT_TOPICS='frigate/available,frigate/events,frigate/stats'
```

docker-compose.yml
```
version: '2.4'
services:
  fevr:
    build:
      context: ${FEVR_CONTEXT}
      dockerfile: Dockerfile
    image: ${FEVR_IMAGE:-ghcr.io/beardedtek-com/fevr:main}
    container_name: ${FEVR_CONTAINER_NAME:-fevr}
    restart: unless-stopped
    environment:
      FRIGATE_URL: "${FRIGATE_URL:-http://frigate.local:5000}"
      FEVR_DEBUG: "${FRIGATE_DEBUG:-true}"
      FEVR_IP: ${FEVR_IP:-192.168.200.2}
      FEVR_PORT: ${FEVR_PORT:-5080}
      FEVR_CONTAINER_NAME: ${FEVR_CONTAINER_NAME:-fevr}
      MQTT_BROKER_URL: "${MQTT_BROKER_URL:-192.168.2.245}"
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT:-1883}
      MQTT_USER: ${MQTT_USER:-}
      MQTT PASS: ${MQTT_PASS:-}
      MQTT_TOPICS: ${MQTT_TOPICS:-'frigate/+'}
    privileged: true
    ports:
      - 5080:5080
    volumes:
     - ./vol/fevr/data/:/var/www/data                              # OPTIONAL: expose /var/www/data folder which contains the SQLite database a>
     - ./vol/fevr/events:/var/www/html/events                      # OPTIONAL: save events to a local folder
     #- nfsevents:/var/www/html/events                             # OPTIONAL: save events to an NFS share
     #- nfsdata:/var/www/data                                      # OPTIONAL: save conig data to an NFS share

#volumes:                                                          # Uncomment this section if you wish to use NFS
#  nfsevents:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NAS_IP},nfsvers=4"
#      device: ":${NAS_EVENTS}"
#  nfsdata:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NAS_IP},nfsvers=4"
#      device: ":${NAS_DATA}"
```
