### DISCUSSION TITLE
v0.6-RC4

### DISCUSSION THREAD

**Discussion by BeardedTek** [BeardedTek-com/fEVR#71] [Announcements]
Getting closer.  No breaking changes, just modifications to make things smoother.

Modified the docker build process
Now using uwsgi instead of built in flask development server
caddy is now installed in the docker image.

<hr /><em>This discussion was created from the release <a href='https://github.com/BeardedTek-com/fEVR/releases/tag/v0.6-RC4'>v0.6-RC4</a>.</em>

**Comment by BeardedTek** [comment]
Unfortunately, I pushed to github docker repo one too many times than they like so the image won't be available until later today.

To use until it is pushed, please do the following:

```
git clone https://github.com/beardedtek-com/fevr
cp template.env .env
```
Edit .env to your use case
```
cd fevr
docker build . -t beardedtek-com/fevr:v0.6-rc4
```
edit docker-compose.yml to look like this:
```
version: '2.4'
services:
  fevr:
    image: beardedtek-com/fevr:v0.6-rc4
    container_name: fevr
    restart: unless-stopped
    privileged: true
    ports:               #Uncomment to export port 5090 if you don't wish to use tailscale
      - 5090:5090
    volumes:
      - ./events:/data/events
    environment:
      FLASK_ENV: ${FLASK_ENV:-development}
      FEVR_PORT: ${FEVR_PORT:-5090}
      TAILSCALE_ENABLE: ${TAILSCALE_ENABLE:-true}
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-fevr}
      TAILSCALE_TAGS: ${TAILSCALE_TAGS}
      MQTT_BROKER_IP: ${MQTT_BROKER_IP}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      MQTT_BROKER_USER: ${MQTT_BROKER_USER}
      MQTT_BROKER_PASS: ${MQTT_BROKER_PASS}
      MQTT_TOPICS: ${MQTT_TOPICS}

```
Then launch as normal:
```
docker-compose up -d
```
