### ISSUE TITLE
Docker compose error

### ISSUE THREAD

**Issue by thundergreen** [BeardedTek-com/fEVR#56]
```
version: '2.4'
services:
  fevr_flask:
    image: ghcr.io/beardedtek-com/fevr-flask:main
    container_name: fevr_flask
    restart: unless-stopped
    privileged: true
    ports:
      - 5090:${FEVR_PORT:-5090}
    volumes:
      - ./:/fevr
    environment:
      FLASK_ENV: ${FLASK_ENV:-}
      FEVR_PORT: ${FEVR_PORT:-5090}
    command: /fevr/run_fevr.sh
  fevr_mqtt:
    image: ghcr.io/beardedtek-com/fevr-flask:main
    container_name: fevr_mqtt
    restart: unless-stopped
    privileged: true
    volumes:
      - ./:/fevr
    command: bash /fevr/run_mqtt_client.sh
```

gives 

![image](https://user-images.githubusercontent.com/13320319/165933703-80550ab2-9d13-46ff-98a6-b27bc5b4993b.png)
